### ISSUE TITLE
Examples not working

### ISSUE THREAD

**Issue by ermolushka** [shadawck/rust-trend#1]
Hey, after the installation and running a basic examples I keep on getting errors

```thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', /root_folder/.cargo/registry/src/github.com-1ecc6299db9ec823/rtrend-0.1.4/src/client.rs:309:71```

Seems like some serialization problems with serde.

**Comment by shadawck** [comment]
Hello @ermolushka I have published a fix. There was some issues with google cookies and the format of the request in the client builder. 

You can use the version v0.1.5 in your Cargo.toml. Thanks for raising this issue :+1:

**Comment by ermolushka** [comment]
Appreciate it, thanks, sees to work. You also need to update the example as it is using

`use rtrend::{Keyword`
instead of
`use rtrend::{Keywords`

**Comment by shadawck** [comment]
yes you're right :smiley:
