### ISSUE TITLE
Code always prints `Response` struct.

### ISSUE THREAD

**Issue by Radvendii** [shadawck/rust-trend#2]
There are some debug statements that seem to be left in the code in https://github.com/shadawck/rust-trend/commit/9daee13c50a3e31eb14a09bd43120e2dc2e79a81

In particular at https://github.com/shadawck/rust-trend/blob/main/src/client.rs#L307-L312

**Comment by shadawck** [comment]
Yes, some debug have been introduced with the last fix. Nice catch :+1: 
It's fixed in main and in version v0.1.6 on crates.io

**Comment by Radvendii** [comment]
Great. Works on my end :-)
